modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cbcaddon"
version = "2.2"
displayName = "Create Big Cannons: Autocannon Revolution"
authors = "QKDream"
description = "Adds APFSDS, APHE, SAP, Shrapnel, Thermite, Multi-Purpose HEAT, Frag Grenade, Smoke/Potion and Heavy Explosive autocannon rounds, High-Velocity Cartridge, and Soul Fire Device."
logoFile = "pack.png"

[[dependencies.cbcaddon]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cbcaddon]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cbcaddon]]
modId = "createbigcannons"
type = "required"
versionRange = "[5.11,6.0)"
ordering = "NONE"
side = "BOTH"
[[dependencies.cbcaddon]]
modId = "cbcmodernwarfare"
type = "required"
versionRange = "[0.0.6,)"
ordering = "AFTER"
side = "BOTH"
